/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package antelope.booleanmodel.formula.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int AND = 9;
  /** RegularExpression Id. */
  int OR = 10;
  /** RegularExpression Id. */
  int IFF = 11;
  /** RegularExpression Id. */
  int IMPLIES = 12;
  /** RegularExpression Id. */
  int LPAR = 13;
  /** RegularExpression Id. */
  int RPAR = 14;
  /** RegularExpression Id. */
  int LBRACKET = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int ASTERISK = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;
  /** RegularExpression Id. */
  int TABLE_ENTRY = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int BIN_DIGIT = 26;
  /** RegularExpression Id. */
  int BLANKS = 27;
  /** RegularExpression Id. */
  int ILLEGAL_CHAR = 28;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"~\"",
    "\"&\"",
    "\"|\"",
    "\"=\"",
    "\"->\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\",\"",
    "\";\"",
    "\":=\"",
    "\"*\"",
    "\"true\"",
    "\"false\"",
    "<IDENTIFIER>",
    "<TABLE_ENTRY>",
    "<LETTER>",
    "<DIGIT>",
    "<BIN_DIGIT>",
    "<BLANKS>",
    "<ILLEGAL_CHAR>",
  };

}
